version: "2.1"

volumes:
  nodemodules_db_admin_administration:
    external: true

services:
  base:
    image: node:alpine
    volumes:
      - nodemodules_db_admin_administration:/app/node_modules
      - .:/app
    working_dir: /app

  install:
    extends:
      service: base
    command: npm i
