version: "3.5"

volumes:
  nodemodules_db_administration:
    external: true
  nodemodules_db_admin_administration:
    external: true

networks:
  logging-network:
    external: true
  internal-network:
    name: internal-network

x-db-administration-app: &db-administration-app
  build:
    context: ./db-administration-app
    dockerfile: ../dockerfiles/Dockerfile-node-app-dev
  expose:
    - 8080
  working_dir: /app
  command: bash -c "/wait && npm run dev"
  volumes:
    - ./db-administration-app:/app
    - nodemodules_db_administration:/app/node_modules
  depends_on:
    - mysql-db
  networks:
    - logging-network
    - internal-network

x-db-admin-administration-app: &db-admin-administration-app
  build:
    context: ./db-admin-administration-app
    dockerfile: ../dockerfiles/Dockerfile-node-app-dev
  expose:
    - 8080
  working_dir: /app
  command: bash -c "/wait && npm run dev"
  volumes:
    - ./db-admin-administration-app:/app
    - nodemodules_db_admin_administration:/app/node_modules
  depends_on:
    - mysql-db
  networks:
    - internal-network
    - logging-network

services:
  db-administration-app-1:
    <<: *db-administration-app
    environment:
      - NODE_ENV=development
      - WAIT_HOSTS=mysql-db:33060
      - APP_DB_NAME=app_db_1
      - LOG_APP_URL=log-app:8080
    ports:
      - 5000:8080

  db-admin-administration-app-1:
    <<: *db-admin-administration-app
    environment:
      - NODE_ENV=development
      - WAIT_HOSTS=mysql-db:33060
      - APP_DB_NAME=app_db_1
      - LOG_APP_URL=log-app:8080
    ports:
      - 5001:8080

  db-administration-app-2:
    <<: *db-administration-app
    environment:
      - NODE_ENV=development
      - WAIT_HOSTS=mysql-db:33060
      - APP_DB_NAME=app_db_2
      - LOG_APP_URL=log-app:8080
    ports:
      - 6000:8080

  db-admin-administration-app-2:
    <<: *db-admin-administration-app
    environment:
      - NODE_ENV=development
      - WAIT_HOSTS=mysql-db:33060
      - APP_DB_NAME=app_db_2
      - LOG_APP_URL=log-app:8080
    ports:
      - 6001:8080

  mysql-db:
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - 33060
    networks:
      - internal-network
    volumes:
      - ./data:/var/lib/mysql
      - ./database/docker-init-scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: test-user
      MYSQL_PASSWORD: test-password
      MYSQL_ROOT_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    networks:
      - internal-network
    depends_on:
      - mysql-db
    ports:
      - 9095:8080
