version: "3.5"

networks:
  persistence-network:
    name: persistence-network

x-db-administration-app: &db-administration-app
  networks:
    - persistence-network

services:
  db-administration-app-1:
    <<: *db-administration-app

  db-admin-administration-app-1:
    <<: *db-administration-app

  db-administration-app-2:
    <<: *db-administration-app

  db-admin-administration-app-2:
    <<: *db-administration-app
